### ISSUE TITLE
在activity的onCreate抛出异常，导致闪退，捕获的问题

### ISSUE THREAD

**Issue by ronindong** [jenly1314/NeverCrash#1]
在activity的oncreate抛出异常，导致闪退时，会出现黑屏，一直卡住的问题

**Comment by jenly1314** [comment]
你提问题的时候，好歹贴下代码或者异常日志吧。

**Comment by ronindong** [comment]
![image](https://cloud.githubusercontent.com/assets/10349678/26052650/bb694e22-3998-11e7-9598-78be9c19a45a.png)
想这段代码，如果放在onClick方法中执行就和你给的gif图一样。
放在activity的onCreate中执行，就会黑屏，卡住。

**Comment by jenly1314** [comment]
不能这样用的，虽说是永不Crash。但是有相对条件的。就是要保证UI主线程的生命周期的正常运行。你这样用，虽然能捕捉到异常，但是你这样写直接影响到了Activity的生命周期，从而导致ANR。
