### ISSUE TITLE
Anr!!!

### ISSUE THREAD

**Issue by 411370845** [jenly1314/NeverCrash#2]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        int a=3/0;
        Log.i("MainActivity","a="+a);
    }
我就添加了这两行代码，APP没报错，但出现了更严重的ANR，作者大神，帮忙分析下

**Comment by jenly1314** [comment]
请参考：https://github.com/jenly1314/NeverCrash/issues/1 的回答。

**Comment by 411370845** [comment]
代码没修改，
用方向键[](url)
![223](https://cloud.githubusercontent.com/assets/11730848/26239149/6fbf2a1e-3cae-11e7-9f2d-f0b8e85a281b.png)

操作，点击button按钮触发Crash，依然会ANR

**Comment by jenly1314** [comment]
模拟器我没试过，请用真机测试。NeverCrash的原理是通过代理全局接管异常捕获，从消息队列循环取消息的方式捕获异常，保证不出现Crash。NeverCrash能保证不Crash，但不保证不出现ANR，ANR是因为UI线程被阻塞。导致阻塞的原因一般是因为执行的任务直接或间接影响到了生命周期。
